package:
  name: cfchecker
  version: "3.1.0.2"

source:
  git_rev: 3.1.0.2
  git_url: https://github.com/Assimila/cfchecker.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cfchecker

about:
  home: https://github.com/Assimila/cfchecker
  license: BSD
  license_file: LICENSE
